import axios from "axios";
import { type Address, createPublicClient, type Hex, http } from "viem";
import { baseSepolia } from "viem/chains";
import { universalEmailRecoveryModule } from "../../../../contracts.base-sepolia.json";
import { universalEmailRecoveryModuleAbi } from "../../../abi/UniversalEmailRecoveryModule.ts";
import config from "../config.ts";
import { GetAccountSaltResponseSchema } from "../types.ts";

/** Computes the guardian address for a given account code and guardian email */
export const computeGuardianAddress = async (
  account: Address,
  accountCode: Hex,
  guardianEmail: string
) => {
  const publicClient = createPublicClient({
    transport: http(config.rpcUrl),
    chain: baseSepolia,
  });

  const getAccountSaltResponse = await axios({
    method: "POST",
    url: `${config.relayerApiUrl}api/getAccountSalt`,
    data: {
      account_code: accountCode.slice(2),
      email_addr: guardianEmail,
    },
  });
  const guardianSalt = GetAccountSaltResponseSchema.parse(
    getAccountSaltResponse.data
  );

  // The guardian address is generated by sending the user's account address and guardian salt to the computeEmailAuthAddress function
  return await publicClient.readContract({
    abi: universalEmailRecoveryModuleAbi,
    address: universalEmailRecoveryModule as `0x${string}`,
    functionName: "computeEmailAuthAddress",
    args: [account, guardianSalt],
  });
};
